version: "3.3"

services:
  database:
    image: mysql:8.0.32
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - "databases:/var/lib/mysql"
      - "./configs/mysql/slow-query.log:/var/log/mysql/mysql-slow.log"
      - "./configs/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"

  webserver:
    build:
      context: "./configs/php/"
    container_name: webserver
    restart: always
    ports:
      - 88:80
    volumes:
      - "./src/:/var/www/html/"
      - "./configs/php/php.ini:/usr/local/etc/php/php.ini"
    depends_on:
      - database

volumes:
  databases: